build_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:1.0 .
    - docker push ${CI_REGISTRY_IMAGE}:1.0
  only:
    - master
