docker:
  stage: build
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker build -t $CI_REGISTRY_IMAGE:${CI_BUILD_TAG} .
   - docker push $CI_REGISTRY_IMAGE:${CI_BUILD_TAG}
  only:
    - tags