FROM ubuntu:16.04

# Install.
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y wget build-essential cmake clang libunwind-dev libicu-dev && \
  wget https://github.com/nodejs/node-chakracore/releases/download/node-chakracore-xplat-7.0.0-pre8/node-chakracore_7.0.0-pre8-Ubuntu16.04_amd64.deb && \
  dpkg -i node-chakracore_7.0.0-pre8-Ubuntu16.04_amd64.deb && \
  rm node-chakracore_7.0.0-pre8-Ubuntu16.04_amd64.deb && \
  rm -rf /var/lib/apt/lists/*

# NPM packages (this takes forever)
RUN npm i -g sequelize-cli